# Homework 1: Python, NumPy, and Pandas
## Author: Amy Esplain
## Date: July 18, 2025

**Instructions:**
- Complete all the questions below.
- Do not remove or rename any code cells.
- You may add cells for testing, but they will not be graded.
- Submit via GitHub Classroom before the deadline.


In [1]:
import numpy as np
import pandas as pd
import statistics


## Part 1: Python Basics

### Q1. Create two variables: an integer `age = 25` and a string `course = "Data Mining"`. Print both variables and their types.

In [2]:
#Create variables
age = 25
course = "Data Mining"

#print values and data types
print(f"The age variable has a value of {age} and data type of {type(age)}.")
print(f"The course variable has a value of '{course}' and data type of {type(course)}.")

print(age)
print(course)
print(type(age))
print(type(course))

The age variable has a value of 25 and data type of <class 'int'>.
The course variable has a value of 'Data Mining' and data type of <class 'str'>.
25
Data Mining
<class 'int'>
<class 'str'>


### Q2. Write a function `is_prime(num)` that uses control structures to determine whether a number is prime.

In [ ]:
# Creating a function that takes an integrer which returns TRUE if prime and FALSE otherwise
def is_prime(num):
    if num <= 1:
        return False
    for i in range(2, int(num**0.5) + 1):
        if num % i == 0:
            return False
    return True

# Checking if the function works by inputting numbers with expected results.
print(f"5 is a prime number?  {is_prime(5)}.")
print(f"7 is a prime number?  {is_prime(7)}.")
print(f"10 is a prime number?  {is_prime(10)}.")


5 is a prime number?  True.
7 is a prime number?  True.
10 is a prime number?  False.


### Q3. Create a dictionary `student_grades` with student names as keys and grades as values. Loop through the dictionary and print each student's name and grade in the format: `Student [Name] has grade [Grade]`.

In [ ]:
# Creating a dictionary that associates student names to letter grades
student_grades = {
    "Amy": 'A',
    "Rami": 'B',
    "Concho": 'C',
    "Brook": 'D',
    "Baylee": 'F'
}

# Creating a for loop to print each student and their grade
for student, grade in student_grades.items():
    print(f"{student} has grade {grade}.")


Amy has grade A.
Rami has grade B.
Concho has grade C.
Brook has grade D.
Baylee has grade F.


### Q4. Use list comprehensions and define reusable functions.

In [ ]:
# Create a tuple list of numbers and that consist of values and its squared amount.
tuple_list = [
    (x, x**2) 
    for x in range(1, 11)
]
print(f"Tuple list is: {tuple_list}")


# Create a function to calculate the mean, median and standard deviation of the tuple list.

def calculate_stats(numbers):
    mean = statistics.mean(numbers)
    median = statistics.median(numbers)
    std_dev = statistics.stdev(numbers)
    return mean, median, std_dev

# Verfying that the function works using a sample list
sample = [1, 2, 3, 4, 5, 6, 7, 8, 9, 10]
stats = calculate_stats(sample)
print(f"Sample numbers: {sample}")
print(f"Of the sample, the mean is: {stats[0]}, median is: {stats[1]}, and standard deviation is: {stats[2]:.2f}.")

Tuple list is: [(1, 1), (2, 4), (3, 9), (4, 16), (5, 25), (6, 36), (7, 49), (8, 64), (9, 81), (10, 100)]
Sample numbers: [1, 2, 3, 4, 5, 6, 7, 8, 9, 10]
Of the sample, the mean is: 5.5, median is: 5.5, and standard deviation is: 3.03.


## Part 2: NumPy Introduction

### Q5. Create NumPy arrays and examine their properties.

In [ ]:
# Creating a a 10x10 matrix with values between 0 and 99.
A = np.arange(100).reshape(10, 10)
print(A)

# Calculate the determinant of the matrix.
det_A = np.linalg.det(A)
print(f"The determinant is: {det_A}")


[[ 0  1  2  3  4  5  6  7  8  9]
 [10 11 12 13 14 15 16 17 18 19]
 [20 21 22 23 24 25 26 27 28 29]
 [30 31 32 33 34 35 36 37 38 39]
 [40 41 42 43 44 45 46 47 48 49]
 [50 51 52 53 54 55 56 57 58 59]
 [60 61 62 63 64 65 66 67 68 69]
 [70 71 72 73 74 75 76 77 78 79]
 [80 81 82 83 84 85 86 87 88 89]
 [90 91 92 93 94 95 96 97 98 99]]
The determinant is: 0.0


### Q6. Perform arithmetic and broadcasting with NumPy arrays.

In [ ]:
# Creating a 1D array with random integers.
array = np.random.rand(10)

# Normalizing the array through applying a min-max normalization so values range 0 to 1
normalized_array = (array - np.min(array)) / (np.max(array) - np.min(array))
print(normalized_array)


[1.         0.04468528 0.00944259 0.66797081 0.14079799 0.27423223
 0.84440466 0.77093841 0.80142647 0.        ]


### Q7. Index, slice, and iterate over NumPy arrays.

In [ ]:
# Creating a 2D array with random integers.
twodimarray = np.random.randint(10, size=(3, 4))

# Printing the array.
print(twodimarray)

# Confirm that the array is two dimensional.
print(f"The array has {twodimarray.ndim} dimensions.")

# Printing all the elements in the third column.
third_column = twodimarray[:, 2]
print(f"The 3rd column is: {third_column}") 

# Loop through the columns and print squared values.
for x in third_column:
    squared_value = x ** 2
    print(f"The squared value of {x} is {squared_value}.")


[[9 9 8 5]
 [7 8 0 0]
 [6 5 0 8]]
The array has 2 dimensions.
The 3rd column is: [8 0 0]
The squared value of 8 is 64.
The squared value of 0 is 0.
The squared value of 0 is 0.


### Q8. Calculate statistical metrics using NumPy.

In [ ]:
# Creating a 2D array with random integers.
twodimarray = np.random.randint(10, size=(3, 4))
print(twodimarray)

# Calculate the mean of rows and columns.
mean_row = np.mean(twodimarray, axis=1)
print(f"The mean of the rows are: {mean_row}") 
mean_col = np.mean(twodimarray, axis=0) 
print(f"The mean of the columns are: {mean_col}")


# Calculating the median of rows and columns.
med_row = np.median(twodimarray, axis=1)
print(f"The median of the rows are: {med_row}") 
med_col = np.median(twodimarray, axis=0) 
print(f"The median of the columns are: {med_col}")



# Calcuating the Variance of rows and columns
var_row = np.var(twodimarray, axis=1)
print(f"The variance of the rows are: {var_row}") 
var_col = np.var(twodimarray, axis=0) 
print(f"The variance of the columns are: {var_row}")





[[7 8 4 7]
 [4 3 3 3]
 [0 7 4 6]]
The mean of the rows are: [6.5  3.25 4.25]
The mean of the columns are: [3.66666667 6.         3.66666667 5.33333333]
The median of the rows are: [7. 3. 5.]
The median of the columns are: [4. 7. 4. 6.]
The variance of the rows are: [2.25   0.1875 7.1875]
The variance of the columns are: [2.25   0.1875 7.1875]


In [ ]:
# Determining the row with maximum variance using np.argmax.
max_var_row = np.argmax(var_row)
print(f"The row with the maximum variance is row {max_var_row} with a variance of {var_row[max_var_row]}.")



The row with the maximum variance is row 2 with a variance of 7.1875.


## Part 3: Pandas Introduction

### Q9. Create and manipulate Series and DataFrames.

In [ ]:
# Creating a series using Pandas and Numpy.
ser = pd.Series(np.random.randint(1,101, size = 10), index = ['a', 'b', 'c', 'd', 'e', 'f', 'g', 'h', 'i', 'j'])
print(ser)

# Converting the series to a dataframe.
df = ser.to_frame(name='Random Numbers')
print(df)

a    35
b    79
c    43
d    31
e    40
f    87
g     2
h    15
i    41
j    69
dtype: int32
   Random Numbers
a              35
b              79
c              43
d              31
e              40
f              87
g               2
h              15
i              41
j              69


### Q10. Import and inspect CSV data using Pandas.

In [ ]:
# Reading the data from a csv file into a dataframe.
scores = pd.read_csv('C:\\Users\\amyes\\OneDrive\\Desktop\\INFO523\\hw-01-EsplaintheCode\\data\\simulated_scores.csv')

# Printing the data type of each column.
print()
print(f"The data type of each column are: \n {scores.dtypes} \n")

# Printing the first 10 rows of the dataframe.
print(f"The first 10 rows are:")
print(scores.head(10))



The data type of each column are: 
 id                    int64
name                 object
score               float64
score_normalized    float64
dtype: object 

The first 10 rows are:
   id     name  score  score_normalized
0   1    Alice   51.0         -1.463583
1   2      Bob   68.0         -0.130677
2   3  Charlie   89.0          1.515854
3   4    Alice   73.0          0.261354
4   5      Bob   96.0          2.064698
5   6  Charlie   74.0          0.339760
6   7    Alice   68.0         -0.130677
7   8      Bob   87.0          1.359042
8   9  Charlie   68.0         -0.130677
9  10    Alice   63.0         -0.522708


### Q11. Clean and manipulate DataFrames (e.g., handle missing values).

In [ ]:
# Creat a random data frame with missing values.
dataframe = pd.DataFrame({
    'Name': ['Brook', 'Baylee', 'Concho', 'Rami', 'Amy','Brook', 'Baylee', 'Concho', 'Rami', 'Amy'],
    'Scores': [51, 68, 89, np.nan, 96, 60, 78, np.nan, 88, 92],
})
print(f"Dataframe with missing value:")
print(dataframe)

# Calculate the median of the scores column.
median_score = dataframe['Scores'].median()
print(f"\n The median of the scores column is: {median_score}")

# Replace missing values with the median score.
dataframe['Scores'] = dataframe['Scores'].fillna(median_score)
print(f"\n Dataframe with missing value replaced with median score {median_score}")
print(dataframe)

# Create a new column with normalized scores using z-score normalization.
dataframe['Score_Normalized'] = round((dataframe['Scores'] - dataframe['Scores'].mean()) / dataframe['Scores'].std(),2)
print(f"\n Dataframe with new column 'Normalized Score':")  
print(dataframe)


Dataframe with missing value:
     Name  Scores
0   Brook    51.0
1  Baylee    68.0
2  Concho    89.0
3    Rami     NaN
4     Amy    96.0
5   Brook    60.0
6  Baylee    78.0
7  Concho     NaN
8    Rami    88.0
9     Amy    92.0

 The median of the scores column is: 83.0

 Dataframe with missing value replaced with median score 83.0
     Name  Scores
0   Brook    51.0
1  Baylee    68.0
2  Concho    89.0
3    Rami    83.0
4     Amy    96.0
5   Brook    60.0
6  Baylee    78.0
7  Concho    83.0
8    Rami    88.0
9     Amy    92.0

 Dataframe with new column 'Normalized Score':
     Name  Scores  Score_Normalized
0   Brook    51.0             -1.89
1  Baylee    68.0             -0.74
2  Concho    89.0              0.70
3    Rami    83.0              0.29
4     Amy    96.0              1.17
5   Brook    60.0             -1.28
6  Baylee    78.0             -0.05
7  Concho    83.0              0.29
8    Rami    88.0              0.63
9     Amy    92.0              0.90


### Q12. Group and aggregate data using Pandas.

In [ ]:
# New dataframe that is grouping by each names and their respective average scores.
group_df = dataframe.groupby('Name')['Scores'].mean().reset_index()
print(f"Unsorted Average for Each Group':")  
print(group_df)

# Sorting the dataframe by the average scores in descending order.
sorted_group_gf = group_df.sort_values(by='Scores', ascending=False)
print(f"\n Descending Order Average for Each Group':")  
print(sorted_group_gf)

Unsorted Average for Each Group':
     Name  Scores
0     Amy    94.0
1  Baylee    73.0
2   Brook    55.5
3  Concho    86.0
4    Rami    85.5

 Descending Order Average for Each Group':
     Name  Scores
0     Amy    94.0
3  Concho    86.0
4    Rami    85.5
1  Baylee    73.0
2   Brook    55.5


## Final Check

In [221]:
# This cell is optional. Run to confirm all cells execute.
print('Notebook structure complete. Review your answers before submission.')

Notebook structure complete. Review your answers before submission.


## Report
While this homework does not require exploratory data analysis, I wanted to include a report section to summarize the key findings and insights from the exercises. I found that working with Python, NumPy, and Pandas was straightforward. The exercises helped solidify my understanding of basic data structures and operations in Python, as well as how to leverage NumPy for numerical computations and Pandas for data manipulation. However, I did encounter some challenges with understanding the broadcasting feature in NumPy, which required additional reading and practice to fully grasp. Additionally, I struggled on the for loops and had to use external resources to answer the question. These resources were cited in the reference section.  Overall, I feel more confident in my ability to work with these libraries and look forward to applying them in future projects.

## References

### [Reference 1](https://www.geeksforgeeks.org/python/python-program-to-check-whether-a-number-is-prime-or-not/), used in part Q2, specifically for creating the `is_prime` function.
### [Reference 2](https://www.geeksforgeeks.org/python/python-iterate-over-columns-in-numpy/), used in part Q7, specifically looping through columns in a NumPy array.
### [Reference 3](https://numpy.org/doc/2.2/reference/generated/numpy.mean.html), used in part Q8, specifically in calculating the mean,median, variance and argmax of a NumPy array.